{"identifier":{"url":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/KyberException\/cipherTextSize(value:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wrong cipher text size"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cipherTextSize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"modules":[{"name":"SwiftKyber"}],"role":"symbol","externalID":"s:10SwiftKyber0B9ExceptionO14cipherTextSizeyACSi_tcACmF","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cipherTextSize","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"KyberException.cipherTextSize(value:)","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/SwiftKyber\/documentation\/SwiftKyber","doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/KyberException"]]},"variants":[{"paths":["\/documentation\/swiftkyber\/kyberexception\/ciphertextsize(value:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftKyber/documentation/SwiftKyber":{"type":"topic","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber","url":"\/documentation\/swiftkyber","title":"SwiftKyber"},"doc://SwiftKyber/documentation/SwiftKyber/KyberException/cipherTextSize(value:)":{"type":"topic","abstract":[{"text":"Wrong cipher text size","type":"text"}],"title":"KyberException.cipherTextSize(value:)","url":"\/documentation\/swiftkyber\/kyberexception\/ciphertextsize(value:)","role":"symbol","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/KyberException\/cipherTextSize(value:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cipherTextSize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://SwiftKyber/documentation/SwiftKyber/KyberException":{"title":"KyberException","kind":"symbol","url":"\/documentation\/swiftkyber\/kyberexception","type":"topic","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/KyberException","navigatorTitle":[{"kind":"identifier","text":"KyberException"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KyberException"}],"abstract":[{"text":"Kyber exceptions","type":"text"}],"role":"symbol"}}}